server:
  port: 8888
security:
  oauth2:
    resource:
       userInfoUri: ${OAUTH_URI:http://localhost:8085/user}
management:
   endpoints:
      web:
         exposure:
           include: "*"
logging:
  level:
     org.springframework.security: debug