server:
   port: 8082
eureka:
  client:
     service-url:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
     register-with-eureka: true
     fetch-registry: true
  instance:
     preferIpAddress: true
spring:
   application:
      name: cambridgeparser
management:
   endpoints:
      web:
         exposure:
           include: "*"
logging:
  level:
    org.springframework.security: debug
security:
  oauth2:
    resource:
       userInfoUri: ${OAUTH_URI:http://localhost:8085/user}

#profiles:
#   active: default