FROM openjdk:10
EXPOSE 8080
ADD /target/microservice-cambridge-parser-1.0-SNAPSHOT.jar microservice-cambridge-parser-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "microservice-cambridge-parser-1.0-SNAPSHOT.jar"]