version: '2.1'
services:
  cambridgeconfig:
       container_name: cambridgeconfig
       restart: always
       image: cambridgeconfig
       build:
         context: ./microservice-config-server
         dockerfile: ./Dockerfile
       ports:
         - "8888:8888"
       expose:
         - 8888
       environment:
         - EUREKA_URI=http://eureka:8761/eureka/
         - CONFIG_URI=http://cambridgeconfig:8888
  eureka:
       container_name: eureka
       restart: always
       image: eureka
       build:
         context: ./microservice-eureka-server
         dockerfile: ./Dockerfile
       ports:
         - "8761:8761"
       expose:
         - 8761
       environment:
         - EUREKA_URI=http://eureka:8761/eureka/
         - CONFIG_URI=http://cambridgeconfig:8888
  cambridgezool:
         container_name: zuul
         restart: always
         image: zuul
         build:
           context: ./microservice-zuul-server
           dockerfile: ./Dockerfile
         ports:
           - "8083:8083"
         expose:
           - 8083
         links:
                - eureka:eureka
                - cambridgeconfig:cambridgeconfig
                - cambridgeparser:cambridgeparser
         depends_on:
                - eureka
                - cambridgeconfig
                - cambridgeparser
         environment:
           - EUREKA_URI=http://eureka:8761/eureka/
           - CONFIG_URI=http://cambridgeconfig:8888
           - CAMBRIDGEPARSER_URI=http://cambridgeparser:8082
  cambridgeparser:
     container_name: cambridgeparser
     restart: always
     image: cambridgeparser
     build:
       context: ./microservice-cambridge-parser
       dockerfile: ./Dockerfile
     ports:
       - "8082:8082"
     expose:
       - 8082
     links:
       - eureka:eureka
       - cambridgeconfig:cambridgeconfig
     depends_on:
       - eureka
       - cambridgeconfig
     environment:
       - EUREKA_URI=http://eureka:8761/eureka/
       - CONFIG_URI=http://cambridgeconfig:8888
  cambridge:
      container_name: cambridge
      restart: always
      image: cambridge
      build:
        context: ./microservice-cambridge
        dockerfile: ./Dockerfile
      ports:
        - "8081:8081"
      expose:
        - 8081
      links:
        - cambridgeconfig:cambridgeconfig
        - cambridgeparser:cambridgeparser
        - eureka:eureka
      depends_on:
        - cambridgeparser
        - eureka
        - cambridgeconfig
      environment:
         - EUREKA_URI=http://eureka:8761/eureka/
         - CONFIG_URI=http://cambridgeconfig:8888

