version: '2.1'
services:
  cambridgeconfig:
       container_name: cambridgeconfig
       restart: always
       image: cambridgeconfig
       build:
         context: ./microservice-config-server
         dockerfile: ./Dockerfile
       mem_limit: 512M
       ports:
         - "8888:8888"
#       links:
         - cambridgeauthentication:cambridgeauthentication
       expose:
         - 8888
       environment:
         - EUREKA_URI=http://eureka:8761/eureka/
         - CONFIG_URI=http://cambridgeconfig:8888
         - OAUTH_URI=http://cambridgeauthentication:8085/user/
         - JAVA_OPT:-Xms256m -Xmx512m XX:+UseContainerSupport
  cambridgeauthentication:
          container_name: cambridgeauthentication
          restart: always
          image: cambridgeauthentication
          build:
            context: ./microservice-authentication-oauth2-server
            dockerfile: ./Dockerfile
          mem_limit: 512M
          ports:
            - "8085:8085"
          expose:
            - 8085
          links:
            - eureka:eureka
          depends_on:
            - eureka
          environment:
             - EUREKA_URI=http://eureka:8761/eureka/
#             - CONFIG_URI=http://cambridgeconfig:8888
             - JAVA_OPT:-Xms256m -Xmx512m XX:+UseContainerSupport
  eureka:
       container_name: eureka
       restart: always
       image: eureka
       build:
         context: ./microservice-eureka-server
         dockerfile: ./Dockerfile
       mem_limit: 512M
       ports:
         - "8761:8761"
#       links:
#         - cambridgeauthentication:cambridgeauthentication
       expose:
         - 8761
       environment:
         - EUREKA_URI=http://eureka:8761/eureka/
         - CONFIG_URI=http://cambridgeconfig:8888
         - OAUTH_URI=http://cambridgeauthentication:8085/user/
         - JAVA_OPT:-Xms256m -Xmx512m XX:+UseContainerSupport
  cambridgezool:
         container_name: zuul
         restart: always
         image: zuul
         build:
           context: ./microservice-zuul-server
           dockerfile: ./Dockerfile
         mem_limit: 512M
         ports:
           - "8083:8083"
         expose:
           - 8083
         links:
           - eureka:eureka
           - cambridgeconfig:cambridgeconfig
           - cambridgeauthentication:cambridgeauthentication
         depends_on:
           - eureka
           - cambridgeconfig
           - cambridgeauthentication
         environment:
           - EUREKA_URI=http://eureka:8761/eureka/
           - CONFIG_URI=http://cambridgeconfig:8888
           - OAUTH_URI=http://cambridgeauthentication:8085/user/
           - JAVA_OPT:-Xms256m -Xmx512m XX:+UseContainerSupport
  cambridge:
      container_name: cambridge
      restart: always
      image: cambridge
      build:
        context: ./microservice-cambridge
        dockerfile: ./Dockerfile
      mem_limit: 512M
      ports:
        - "8081:8081"
      expose:
        - 8081
      links:
        - cambridgeconfig:cambridgeconfig
        - eureka:eureka
        - cambridgeauthentication:cambridgeauthentication
      depends_on:
        - eureka
        - cambridgeconfig
        - cambridgeauthentication
      environment:
         - EUREKA_URI=http://eureka:8761/eureka/
         - CONFIG_URI=http://cambridgeconfig:8888
         - OAUTH_URI=http://cambridgeauthentication:8085/user/
         - JAVA_OPT:-Xms256m -Xmx512m XX:+UseContainerSupport