version: '2.1'
services:
  eureka:
       container_name: eureka
       restart: always
       image: eureka
       build:
         context: ./microservice-config
         dockerfile: ./Dockerfile
       ports:
         - "8761:8761"
       expose:
         - 8761
       environment:
         - EUREKA_URI=http://eureka:8761/eureka/


