version: '2.1'
services:
  eureka:
       container_name: eureka
       restart: always
       image: eureka
       build:
         context: ./microservice-eureka-server
         dockerfile: ./Dockerfile
       ports:
         - "8761:8761"
       expose:
         - 8761
       environment:
         - EUREKA_URI=http://eureka:8761/eureka/
  cambridgeparser:
     container_name: cambridgeparser
     restart: always
     image: cambridgeparser
     build:
       context: ./microservice-cambridge-parser
       dockerfile: ./Dockerfile
     ports:
       - "8082:8082"
     expose:
       - 8082
     links:
       - eureka:eureka
     depends_on:
       - eureka
     environment:
       - EUREKA_URI=http://eureka:8761/eureka/
  cambridge:
      container_name: cambridge
      restart: always
      image: cambridge
      build:
        context: ./microservice-cambridge
        dockerfile: ./Dockerfile
      ports:
        - "8081:8081"
      expose:
        - 8081
      links:
        - cambridgeparser:cambridgeparser
        - eureka:eureka
      depends_on:
        - cambridgeparser
        - eureka
      environment:
         - EUREKA_URI=http://eureka:8761/eureka/

