server:
   port: 8084
eureka:
  client:
     service-url:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
     register-with-eureka: true
     fetch-registry: true
  instance:
     preferIpAddress: true
spring:
   application:
      name: cambridgecqrs
   liquibase:
     change-log: classpath:liquibase/db-changelog-1.0.xml
     default-schema: cambridge
   datasource:
     url: ${DB_URL:jdbc:mysql://localhost:3306/cambridge?useUnicode=true&amp;useJDBCCompliantTimezoneShift=true&amp;useLegacyDatetimeCode=false&amp;serverTimezone=UTC}
     username: root
     password: ilya1302
     driver-class-name: com.mysql.jdbc.Driver
management:
   endpoints:
      web:
         exposure:
           include: "*"
logging:
  level:
     org.springframework.security: debug
security:
  oauth2:
    resource:
       userInfoUri: ${OAUTH_URI:http://localhost:8085/user}


