server:
   port: 8085
eureka:
  client:
     service-url:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
     register-with-eureka: true
     fetch-registry: true
  instance:
     preferIpAddress: true
spring:
   application:
      name: cambridgeauthentication
management:
   endpoints:
      web:
         exposure:
           include: "*"
security:
  oauth2:
    resource:
       userInfoUri: ${OAUTH_URI:http://localhost:8085/user}
#logging:
#  level:
#     org.springframework.security: debug


