server:
   port: 8081
eureka:
  client:
     service-url:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
     register-with-eureka: true
     fetch-registry: true
  instance:
     preferIpAddress: true
spring:
   application:
      name: cambridge

#profiles:
#   active: default