server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
   application:
     name: eureka
management:
   endpoints:
      web:
         exposure:
           include: "*"
security:
  oauth2:
    resource:
       userInfoUri: ${OAUTH_URI:http://localhost:8085/user}