server:
   port: 8083
eureka:
  client:
     service-url:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
     register-with-eureka: true
     fetch-registry: true
  instance:
     preferIpAddress: true
spring:
   application:
      name: cambridgezool
   devtools:
      remote:
        secret: thisismysecret
management:
   endpoints:
      web:
         exposure:
           include: "*"
zuul:
  routes:
     cambridgeparser: /parser/**
  ignored-services: "*"
  sensitive-headers: Cookie,Set-Cookie
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
#ribbon:
#  ConnectTimeout: 6000
#  ReadTimeout: 60000