FROM openjdk:10
EXPOSE 8085
ADD /target/microservice-authentication-oauth2-server-1.0-SNAPSHOT.jar microservice-authentication-oauth2-server-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "microservice-authentication-oauth2-server-1.0-SNAPSHOT.jar"]