FROM openjdk:10.0.2-jre-slim
EXPOSE 8085
ADD microservice-authentication-oauth2-server-1.0-SNAPSHOT.jar microservice-authentication-oauth2-server-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "microservice-authentication-oauth2-server-1.0-SNAPSHOT.jar"]