FROM openjdk:10
EXPOSE 8888
ADD /target/microservice-config-server-1.0-SNAPSHOT.jar microservice-config-server-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "microservice-config-server-1.0-SNAPSHOT.jar"]